import argparse
import os
import random
from os.path import join

prompts = [
    'A speaker is giving a speech.',
    'A speaker is giving a speech on the stage.',
    'An excellent speaker delivers a speech on stage.',
    'A person is speaking with accompanying body gestures.',
    'Speaking with accompanying movements.',
    'Deliver a speech on stage.',
    'A person is speaking',
    'A presenter is making a speech.',
    'A lecturer is speaking on the stage.',
    'A gifted orator is delivering a speech on stage.',
    'An individual is speaking with added physical gestures.',
    'Speaking while using body language.',
    'Give a speech on the stage.',
    'Someone is speaking',
    'An individual gives a talk.',
    'A person is delivering a presentation on stage.',
    'A dynamic speaker is addressing an audience.',
    'Engaging in speech with accompanying gestures.',
    'Speaking on stage with enthusiasm.',
    'A person is giving a lecture',
    'Someone is delivering a keynote address on stage.',
    'A speaker presents a talk with hand gestures.',
    'Conveying a message on stage.',
    'Communicating with body language while speaking.',
    'A person addresses the crowd.',
    'An orator speaks with passion on stage.',
    'Delivering an address with physical movements.',
    'Public speaking with expressive gestures.',
    'Orating on stage with flair.',
    'A speaker communicates a message.',
    'Giving a talk with accompanying actions.',
    'A speaker is articulating their thoughts on stage.',
    'Expressing ideas with hand movements while speaking.',
    'A person gives a discourse on stage.',
    'Making a presentation with gestures.',
    'An individual is addressing an audience.',
    'Speaking publicly with body movements.',
    'A presenter is engaging the audience on stage.',
    'A person is articulating a speech with gestures.',
    'Delivering a public address on stage.',
    'Conveying thoughts with accompanying body language.',
    'An individual is making a statement on stage.',
    'Speaking with physical expression.',
    'A speaker is sharing ideas on stage.',
    'A person is talking with gestures.',
    'Addressing an audience with a speech.',
    'Speaking on stage with body movements.',
    'Communicating a message with physical gestures.',
    'A speaker is presenting a topic on stage.',
    'An orator is expressing thoughts with body movements.',
    'Delivering a speech with enthusiasm on stage.',
    'A person is making a declaration.',
    'Orating with expressive body language.',
    'A speaker articulates on stage with movements.',
    'Presenting a speech with physical actions.',
    'A person is communicating a message on stage.',
    'Engaging in public speaking with gestures.',
    'A presenter is speaking with emphasis on stage.',
    'A speaker delivers a message with body language.',
    'Addressing the audience with a speech on stage.',
    'Speaking and using hand gestures for emphasis.',
    'An individual is giving a talk with movements.',
    'Presenting ideas on stage with physical expression.',
    'A person is engaging in a speech.',
    'Orating on stage with dynamic gestures.',
    'A speaker is talking with accompanying actions.',
    'Delivering a lecture with body movements.',
    'A presenter speaks with enthusiasm on stage.',
    'Communicating on stage with hand gestures.',
    'A speaker is addressing with physical movements.',
    'Giving a presentation with accompanying gestures.',
    'An individual is making a speech on stage.',
    'Speaking with gestures for emphasis.',
    'A person is talking on stage with movements.',
    'Orating with physical expression on stage.',
    'A speaker delivers a talk with body language.',
    'Engaging in a speech with dynamic gestures.',
'A presenter is articulating a topic on stage.',
    'A communicator is speaking with gestures on stage.',
    'Delivering an oration with expressive movements.',
    'A public speaker is giving a lecture with body language.',
    'An orator delivers a talk with passion on stage.',
    'A lecturer is engaging the audience with body gestures.',
    'Speaking publicly with dynamic movements.',
    'A person is giving an address with accompanying actions.',
    'An individual is presenting a topic with hand gestures.',
    'A speaker is lecturing with physical expression.',
    'Orating with enthusiasm and physical gestures on stage.',
    'A presenter is giving a speech with expressive body language.',
    'A speaker is addressing the crowd with movements.',
    'Conveying a lecture with body language on stage.',
    'Publicly speaking with engaging gestures.',
    'Delivering a talk with body movements for emphasis.',
    'A person is making a speech with expressive actions.',
    'An orator is engaging in public speaking with gestures.',
    'A speaker is delivering a message with physical expression.',
    'Communicating a topic on stage with body gestures.',
    'Addressing an audience with expressive body language.',
    'Speaking on stage with physical articulation.',
    'Giving a presentation with dynamic body language.',
    'A lecturer is speaking with added gestures.',
    'An individual presents a speech with hand movements.',
    'Orating with flair and physical expressions on stage.',
    'A speaker expresses ideas with body movements.',
    'Presenting on stage with engaging body gestures.',
    'A communicator is delivering a talk with body language.',
    'Speaking with vitality and gestures on stage.',
    'An orator is making a powerful statement with body movements.',
    'Delivering a powerful speech with physical gestures on stage.',
    'A person is speaking on stage with dynamic body language.',
    'A presenter is giving an address with physical emphasis.',
    'Communicating a lecture with expressive body movements.',
    'Orating with passion and body gestures.',
    'A speaker is giving a discourse with physical actions.',
    'Presenting a topic on stage with engaging gestures.',
    'A person is addressing the audience with body language.',
    'Speaking on stage with expressive body movements.',
    'Giving a lecture with physical expressions.',
    'A speaker is engaging the audience with body gestures.',
    'An individual is orating with dynamic movements on stage.',
    'Delivering a public talk with engaging body language.',
    'A presenter is communicating ideas with gestures.',
    'Speaking with body language for emphasis on stage.',
    'A person is giving an oration with expressive movements.',
    'An orator is speaking with passion and body gestures.',
    'Delivering a keynote address with physical expressions.',
    'A speaker is making a statement with body movements.',
    'Presenting a speech with vitality and body gestures.',
    'A person is engaging in oratory with dynamic gestures.',
    'Communicating on stage with expressive body language.',
    'A speaker is delivering a lecture with hand gestures.',
    'Giving a public address with engaging body movements.',
    'A presenter is orating with expressive physical gestures.',
    'Speaking on stage with fervor and body language.',
    'An individual is delivering a talk with physical expression.',
    'Orating on stage with powerful body gestures.',
    'Delivering a persuasive speech with body movements.',
    'A speaker is making a presentation with hand movements.',
    'Communicating with the audience through body gestures.',
    'A person is giving a talk with dynamic body language.',
    'Presenting on stage with expressive hand gestures.',
    'An orator is speaking with physical emphasis.',
    'Delivering a powerful oration with engaging gestures.',
    'A speaker is addressing with hand movements on stage.',
    'Giving a speech with emphasis on physical gestures.',
    'An individual is presenting with dynamic body language.',
    'Speaking with enthusiasm and physical gestures.',
    'A person is orating with expressive body movements.',
    'Delivering a presentation with engaging body language.',
    'A speaker is talking with emphasis on hand gestures.',
    'Communicating a message with physical expressions on stage.',
    'Presenting a lecture with body movements for emphasis.',
    'An orator is delivering a speech with dynamic gestures.',
    'Giving a talk with expressive body language on stage.',
    'A speaker is making a statement with engaging movements.',
    'Communicating ideas with hand gestures on stage.',
    'Presenting a speech with physical articulation.',
    'A person is speaking with body gestures for emphasis.',
    'An individual is giving a lecture with dynamic body language.',
    'Orating with engaging physical expressions on stage.',
    'Delivering a talk with expressive hand movements.',
    'A speaker is addressing the audience with body language.',
    'Giving a presentation with physical emphasis on stage.',
    'An orator is speaking with vitality and gestures.',
    'Delivering an address with dynamic body movements.',
    'A speaker is communicating a topic with physical gestures.',
    'Presenting ideas with expressive body language on stage.',
    'A person is making a speech with engaging gestures.',
    'Orating with passion and expressive body movements.',
    'Delivering a lecture with hand gestures for emphasis.',
    'A speaker is giving an address with dynamic body language.',
    'Communicating a message with engaging physical expressions.',
    'Presenting a topic with vitality and body gestures on stage.',
    'A person is speaking with expressive body movements.',
    'An individual is orating with hand gestures for emphasis.',
    'Giving a speech with dynamic and engaging body language.',
    'A speaker is making a presentation with expressive gestures.',
    'Communicating on stage with dynamic body movements.',
    'Presenting a speech with engaging hand movements.',
    'A person is delivering a talk with body language emphasis.',
    'A presenter eloquently speaks with accompanying movements.',
    'An individual delivers a speech with added physical expression.',
    'A speaker talks on stage, using gestures for impact.',
    'Addressing an audience with a speech, enhanced by body language.',
    'A communicator on stage using hand gestures while speaking.',
    'Orating with the aid of expressive body movements.',
    'A speaker articulates a topic with added physical gestures.',
    'Presenting a lecture on stage with dynamic body expressions.',
    'A person speaks with engaging movements.',
    'A lecturer communicates with the audience using hand movements.',
    'Delivering an address with the support of body gestures.',
    'A speaker on stage, expressing ideas with hand gestures.',
    'Giving a talk with the accompaniment of body movements.',
    'An orator uses physical gestures while delivering a speech.',
    'Speaking on stage, supplemented by expressive body language.',
    'A presenter makes a speech with emphatic body movements.',
    'Orating with the enhancement of physical expressions.',
    'A speaker delivers a message using expressive gestures.',
    'Communicating a lecture with the addition of body movements.',
    'Giving a presentation with the support of hand gestures.',
    'An individual speaks on stage, using body language for emphasis.',
    'A speaker conveys a message with dynamic physical gestures.',
    'Delivering a speech on stage with the accompaniment of movements.',
    'Speaking with a blend of words and expressive gestures.',
    'A presenter articulates a topic with dynamic body language.',
    'Orating with a combination of speech and body movements.',
    'A speaker on stage uses gestures to enhance the message.',
    'Giving a talk that includes expressive hand movements.',
    'An orator communicates with added physical expressions.',
    'Speaking with the support of emphatic body gestures.',
    'A communicator delivers a speech with engaging body language.',
    'Presenting ideas on stage with the aid of physical movements.',
    'A person talks with the embellishment of hand gestures.',
    'A speaker delivers a discourse with body language for emphasis.',
    'Conveying a message on stage with expressive movements.',
    'An individual gives a talk with the addition of gestures.',
    'Orating on stage, using body expressions for emphasis.',
    'A speaker makes a statement with the support of physical gestures.',
    'Presenting a topic with the enhancement of body movements.',
    'Speaking with a combination of verbal and physical expression.',
    'A lecturer delivers a speech with dynamic body gestures.',
    'An orator speaks with the accompaniment of hand movements.',
    'A presenter conveys ideas with engaging body language.',
    'Delivering a lecture with the addition of expressive gestures.',
    'Communicating a topic with the support of body movements.',
    'A person makes a speech with physical gestures for impact.',
    'A speaker articulates ideas with the aid of body language.',
    'Speaking on stage with the embellishment of hand gestures.',
    'An individual presents a talk with dynamic body movements.',
    'Orating with a blend of speech and expressive body language.',
    'A communicator gives a lecture with engaging physical gestures.',
    'Presenting a message with the support of hand movements.',
    'A speaker talks with the addition of physical expressions.',
    'Delivering a speech with a combination of verbal and physical expression.',
    'Communicating on stage with the aid of body gestures.',
    'An orator gives a talk with the enhancement of movements.',
    'Speaking with the support of dynamic body language.',
    'A person delivers a presentation with expressive hand gestures.',
    'Orating with the accompaniment of physical expressions.',
    'A speaker conveys a message with the support of body movements.',
    'Presenting a topic on stage with engaging body gestures.',
    'A lecturer speaks with the addition of expressive movements.',
    'Delivering a lecture with the enhancement of body language.',
    'Communicating a speech with dynamic physical gestures.',
    'An individual talks with the accompaniment of hand movements.',
    'A speaker articulates a topic with engaging body expressions.',
    'Speaking on stage with the support of expressive gestures.',
    'Orating with a blend of verbal and physical communication.',
    'A presenter gives a speech with the addition of body movements.',
    'Presenting ideas with dynamic hand gestures.',
    'A communicator speaks with engaging body language on stage.',
    'Delivering a message with the support of physical expressions.',
    'Communicating a lecture with the addition of body gestures.',
    'An orator delivers a talk with engaging physical movements.',
    'Speaking with a combination of words and body language.',
    'A person makes a speech with the aid of expressive gestures.',
    'A speaker talks with the accompaniment of dynamic movements.',
    'Orating with the enhancement of physical gestures.',
    'A speaker enhances their speech with body movements.',
    'A communicator conveys their message with physical gestures on stage.',
    'A person articulates their point with accompanying hand movements.',
    'A lecturer integrates body language into their speech.',
    'An individual uses expressive gestures while speaking.',
    'A presenter enlivens their speech with dynamic movements.',
    'A speaker on stage accentuates points with physical expressions.',
    'Giving an oration augmented by expressive body language.',
    'A speaker adds emphasis to their talk with hand gestures.',
    'Communicating on stage, supplemented by body movements.',
    'A person delivers a discourse, punctuated with gestures.',
    'A speaker employs body gestures to enhance communication.',
    'Speaking with added physical emphasis for clarity.',
    'Orating with a mixture of verbal and physical articulation.',
    'A presenter uses body language to reinforce their message.',
    "A speaker's lecture is interspersed with expressive movements.",
    'An individual speaks, using gestures for greater impact.',
    'Delivering a talk with the addition of dynamic body gestures.',
    'Communicating a point with the aid of physical expressions.',
    'An orator blends speech with expressive body movements.',
    'A person gives a lecture, using body language for emphasis.',
    'Speaking on stage, enriched with physical gestures.',
    'A presenter emphasizes points with hand movements.',
    "An individual's speech is enhanced by dynamic gestures.",
    'A communicator delivers a message with physical articulation.',
    'Orating with gestures to add emphasis and clarity.',
    'A speaker integrates hand gestures into their presentation.',
    'Delivering a speech, complemented by expressive body language.',
    'A person conveys their message with the aid of gestures.',
    'Communicating effectively with the addition of body movements.',
    'A speaker uses physical expressions to enrich their speech.',
    'An individual delivers a talk, augmented by hand gestures.',
    'Speaking with the support of dynamic body expressions.',
    'Orating with added physical emphasis for effect.',
    "A presenter's speech is punctuated with gestures.",
    "A speaker's communication is enhanced by body language.",
    'Delivering a message with the complement of physical gestures.',
    'An orator uses body movements to add depth to their speech.',
    'Communicating with the addition of expressive hand movements.',
    'A person speaks, employing body language for added impact.',
    'Speaking on stage with the inclusion of physical gestures.',
    'A presenter highlights points with dynamic body movements.',
    "An individual's oration is enriched with hand gestures.",
    "A speaker's presentation includes expressive body language.",
    'Delivering a talk with the support of body gestures.',
    'Communicating ideas with added physical expressions.',
    'Orating with the aid of dynamic physical movements.',
    'A person uses gestures to enhance their speech.',
    'Speaking with the inclusion of expressive body movements.',
    'A presenter accentuates their speech with physical gestures.',
    "A speaker's delivery is augmented by body language.",
    'Communicating a lecture with the addition of hand movements.',
    'An orator speaks, integrating body gestures for emphasis.',
    'Delivering a presentation with the aid of physical expressions.',
    "A person's speech is complemented by expressive movements.",
    'Speaking on stage, enhanced with body gestures.',
    'A presenter emphasizes their points with hand movements.',
    'An individual uses body language to add depth to their speech.',
    'Communicating with the support of dynamic gestures.',
    "A speaker's oration includes expressive body movements.",
    'Delivering a lecture with the inclusion of physical gestures.',
    "A person's communication is enriched by body language.",
    'Speaking with added physical emphasis for greater impact.',
    'Orating with the support of expressive hand gestures.',
    "A presenter's talk is punctuated with dynamic movements.",
    'A speaker employs gestures to enhance their delivery.',
    'Communicating a message with the addition of body expressions.',
    "An orator's speech is complemented by physical movements.",
    'Delivering a talk, enriched with expressive body gestures.',
    'A person speaks, using body language for emphasis.',
    'Speaking on stage with the aid of physical expressions.',
    'A presenter accentuates their message with hand movements.',
    "An individual's lecture includes dynamic body gestures.",
    "A speaker's delivery is enhanced by expressive movements.",
    'Communicating with the inclusion of body language.',
    'Orating with the aid of hand gestures for emphasis.',
    "A person's presentation is enriched with physical movements.",
    'Speaking with dynamic body gestures for added clarity.',
    'A presenter uses physical expressions to reinforce their speech.',
    "A speaker's oration is augmented by hand movements.",
    'Delivering a speech, complemented by dynamic body language.',
    'Communicating a topic with the support of physical gestures.',
    'An orator integrates body movements into their delivery.',
    'Speaking with the addition of expressive gestures.',
    "A presenter's speech includes physical articulation.",
    'A speaker employs body language to enrich their talk.',
    'Delivering a lecture with the support of hand gestures.',
    'Communicating effectively with added body movements.',
    'A person uses expressive gestures to enhance their speech.',
    'Speaking on stage with the inclusion of dynamic body language.',
    'A presenter emphasizes their points with expressive movements.',
    "An individual's speech is augmented by body gestures.",
    "A speaker's presentation is enhanced with physical expressions.",
    'Delivering a message with the aid of body language.',
    'Communicating a lecture with dynamic physical gestures.',
    'Orating with the inclusion of hand movements for emphasis.',
    "A person's talk is enriched with expressive body movements.",
    'Speaking with the support of physical gestures.',
    'A presenter accentuates their lecture with body language.',
    'A speaker employs dynamic movements to enhance their speech.',
    'Communicating a topic with the addition of expressive gestures.',
    'An orator integrates expressive body movements into their oration.'

]


def get_token(text):
    tokens = []
    for word in text.split(' '):
        tokens.append(word + '/UNK')
    return ' '.join(tokens)


def make_file(save_path, texts):
    rows = ''
    for text in texts:
        token = get_token(text)
        rows += text + '#' + token + '#0.0#0.0\n'

    with open(save_path, 'w') as fp:
        fp.write(rows)

if __name__ == '__main__':
    args = argparse.ArgumentParser('generate text file for aist++')
    args.add_argument('--vec_root', default='data/beat/vecs_joints_22')
    args.add_argument('--text_root', default='data/beat/texts')
    args=args.parse_args()
    os.makedirs(args.text_root, exist_ok=True)
    for file in os.listdir(args.vec_root):
        save_path = join(args.text_root, file.replace('.npy', '.txt'))
        texts = random.sample(prompts, 3)
        make_file(save_path, texts)
